### ISSUE TITLE
12 hour for the pico w as well 

### ISSUE THREAD

**Issue by Steph1116** [jake1164/Pico-RGB-Matrix-Clock#1]
Thanks for fixing the pico 12 hour time, I’m using the pico w code de which I should have mentioned. Could you add it to that one as well? Thanks!

**Comment by jake1164** [comment]
Just added it.


________________________________
From: Steph1116 ***@***.***>
Sent: Thursday, January 12, 2023 9:15 PM
To: jake1164/Pico-RGB-Matrix-Clock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jake1164/Pico-RGB-Matrix-Clock] 12 hour for the pico w as well (Issue #1)


Thanks for fixing the pico 12 hour time, I’m using the pico w code de which I should have mentioned. Could you add it to that one as well? Thanks!

**Comment by Steph1116** [comment]
Thank you!!!

I hate to ask. The waveshare team has released an update to their demo. The code from their site originally had my clock display upside down, your code does the same. This doesn't cause a whole lot of issues but my whole unit has to sit on a surface rather than being able to be hung from the mount holes. Is there a way to implement their updated code, along with the newly added 12 hour code to the pico w?

**Comment by Steph1116** [comment]
Also I noticed having the code run that after awhile my screen says "code done running" this was just the unit unplugged from my pc just powered by the 5v wall plug.

**Comment by jake1164** [comment]
Yes I noticed the demo code was upside down and was just not sure if it was something with my unit or not.  I will have to look at the updated code, thanks for the heads up.
________________________________

**Comment by jake1164** [comment]
I noticed that as well and was going to look into it and see if it was a circuit python issue or something with the code. I will hopefully have an update this weekend.
________________________________

**Comment by jake1164** [comment]
While cant say for sure but I am not seeing the code has finished running issue since updating. (fingers crossed)

**Comment by Steph1116** [comment]
I'm not sure exactly how long after I plugged the unit in and using as I would for a display clock, but I did wake up to the white text saying code done running. Just wanted to update you. Absolutely no rush for me as I haven't fully implemented this as a clock into my home. I'm still using the pico w to learn code and try out a few things. My end goal is obtaining a second pico w and then installing the original into this clock and mount it on the wall to display. 

Thanks again!

**Comment by jake1164** [comment]
I would do a fresh pull and copy all the files over again.

**Comment by Steph1116** [comment]
Downloaded your latest updated code and it's been holding strong for the last 12 hours. It's also in the correct orientation. Much appreciate the updates and looking forward to any additions you do in the future, including the possibility of the weather. I'll update you if it doesn't last overnight. Thanks again

**Comment by Steph1116** [comment]
Hi, I'd thought you'd like to know that I've been running your code now since my last message to you and it has been running flawlessly. Thanks so much again for all the fixes, I've spent so much money and time just trying to get a clock, this is truly perfect!

**Comment by jake1164** [comment]
Great to hear!  I am excited to make this offer a little more than a clock soon!
________________________________

**Comment by Steph1116** [comment]
hi, everything is running smoothly. I bought a new pico W and im looking to use it with my 64x64 rgb panel, but i cant find any clock code for it. As a learning tool for me, any way to take this code and have it work on the 64x64?

**Comment by jake1164** [comment]
If your talking just plugging the waveshare backed into a bigger panel then I guess in theory to test it just add a new line4, set the x & y to something on the lower half, add a line4.text="something", append the line to the Group and it should work in theory

**Comment by Steph1116** [comment]
I just have the pico w and the 64x64 panel with the 16 wires it came with. I don't have any other hardware. So I'm going to assume it's just simpler to write a whole new code. Not to worry my friend, I highly appreciate the reply and the code you provided here to get the clock up and running. Take care!
